Models/VoteDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IndianCitizenService.Models
{
    public class RenderMapDetail
    {
        public int ColorIndex { get; set; }

        public double LocLalitudeStart { get; set; }

        public double LocLalitudeEnd { get; set; }

        public double LocLongitudeStart { get; set; }

        public double LocLongitudeEnd { get; set; }
    }

    public class VoteDetail
    {
        public long UserId { get; set; }

        public long Id { get; set; }

        public int GradeValue { get; set; }

        public LocationDetail LocationDetail { get; set; }
    }

    public class LocationDetail
    {
        public long Id { get; set; }

        public double LocLalitudeStart { get; set; }

        public double LocLalitudeEnd { get; set; }

        public double LocLongitudeStart { get; set; }

        public double LocLongitudeEnd { get; set; }

    }
}

Controllers/BaseController.cs
using IndianCitizenService.Common;
using IndianCitizenService.Handler;
using IndianCitizenService.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace IndianCitizenService.Controllers
{


    public class BaseController : Controller
    {
        private static IList<VoteDetail> voteCollection;
        private static LocationDetail locationDetail;
        private static bool IsRoadCleaned;
        public BaseController()
        {
            if (voteCollection == null)
                voteCollection = new List<VoteDetail>();
            if(locationDetail == null)
            locationDetail = new LocationDetail()
            {
                Id = 1,
                LocLalitudeStart = 13.02804601720666,
                LocLalitudeEnd = 80.17689228057861,
                LocLongitudeStart = 13.029739344613546,
                LocLongitudeEnd = 80.17709612846375
            };
            
        }
        //
        // GET: /Base/
        public ActionResult Index()
        {
            ViewBag.Notification = IsRoadCleaned;
            return View();
        }

        public ActionResult LiveMap()
        {
            LiveTrackHandler handler = new LiveTrackHandler();
            var detail = handler.getVoteDetail(voteCollection);
            return View(detail);
        }

        public ActionResult Logon()
        {
            return View();
        }

        public ActionResult VoteAction(int selectedCategory)
        {
            VoteDetail renderDetail = new VoteDetail()
            {
                LocationDetail= locationDetail,
                GradeValue = LiveTrackHandler.getGrade(selectedCategory),
                Id = 20
            };
            voteCollection.Add(renderDetail);
            if (IsRoadCleaned) { 
                IsRoadCleaned = false;
            }
            return Json(true);
        }

        public ActionResult SaveStatus()
        {
            IsRoadCleaned = true;
            return Json(null);
        }

        public ActionResult ValidateUser(string userId, string password)
        {
            if ((userId.Equals(AppConstant.CitizenUserId) || userId.Equals(AppConstant.CitizenUserId1)  || userId.Equals(AppConstant.CitizenUserId) ) && password.Equals(AppConstant.CitizenPassword))
            {
                return Json(AppConstant.HostName + AppConstant.BaseController + AppConstant.FileHash.ToString() + AppConstant.ViewUserMap);

            }
            else if (userId.Equals(AppConstant.AdminUserID) && password.Equals(AppConstant.AdminPassword))
                return Json(AppConstant.HostName + AppConstant.BaseController + AppConstant.FileHash.ToString() + AppConstant.ViewLiveMap);
            else
                return Json(false);
        }

        public ActionResult ReportIndex(int? reportType)
        {

            return View(reportType);
        }

        public ActionResult PieChart()
        {
            var key = new Chart(width: 600, height: 400)
              .AddSeries(
                  chartType: "pie",
                  legend: "City Health Status",
                  xValue: new[] { "Low", "Medium", "High", "Concern free" },
                  yValues: new[] { "2", "28", "30", "40" })


              .Write();

            return null;
        }

        public ActionResult BarChart()
        {
            var key = new Chart(width: 600, height: 400)
                  .AddSeries(
                      chartType: "bar",
                      legend: "City Health Status",
                      xValue: new[] { "High", "Medium", "Low", "Concern free" },
                      yValues: new[] { "30", "28", "2", "40" })
                  .Write();

            return null;
        }

        public ActionResult AreawiseChart()
        {
            var key = new Chart(width: 600, height: 400)
              .AddSeries(
                  chartType: "bar",
                  legend: "City Health Status",
                  yValues: new[] { "22", "28", "30", "20" },
                  xValue: new[] { "Guindy", "Nandambakkam", "Manapakkam", "Porur" })


              .Write();

            return null;
        }

        public ActionResult CityWise()
        {
            var key = new Chart(width: 600, height: 400)
              .AddSeries(
                  chartType: "bar",
                  legend: "City Health Status",
                  xValue: new[] { "Chennai", "Bangalore", "Hyderabad", "Mumbai" },
                  yValues: new[] { "32", "28", "20", "20" })


              .Write();

            return null;
        }

    }
}

Views/Base/Index.cshtml
@using IndianCitizenService.Common;
@{
    ViewBag.Title = "Index";
}

<header>
    <center>
        Indian CitizenService
    </center>
</header>
<span class="badge" id="notification">1</span>
<span class="glyphicon glyphicon-log-out" id="logout"></span>

<div id="map" style="width:80%;height:80%;"></div>

<div id="votePoll">
    <table cellpadding="10">
        <tr>
            <td colspan="2"><center><p class="label label-default">choose your area category</p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button id="closeCategory" class="btn btn-danger">X</button></center></td>
        </tr>
        <tr>
            <td>
                <img src="@Url.Content("~/Content/Images/category1.jpg")" width="150" height="125" class="voteImg" onclick="toggleMapForSelectedImage(this);" id="category1" />
            </td>
            <td>
                <img src="@Url.Content("~/Content/Images/category2.jpg")" width="150" height="125" class="voteImg" onclick="toggleMapForSelectedImage(this);" id="category2" />
            </td>
        </tr>
        <tr>
            <td>
                <img src="@Url.Content("~/Content/Images/category3.jpg")" width="150" height="125" class="voteImg" onclick="toggleMapForSelectedImage(this);" id="category3" />
            </td>
            <td>
                <img src="@Url.Content("~/Content/Images/category4.jpg")" width="150" height="125" class="voteImg" onclick="toggleMapForSelectedImage(this);" id="category4" />
            </td>
        </tr>
        <tr>
            <td colspan="2"><center><textarea placeholder="Comments....." id="txtComment"></textarea></center></td>
        </tr>
        <tr>
            <td colspan="2"><center><button id ="btnPostVote" onclick="PostVote()" class="btn btn-primary">vote</button></center></td>
        </tr>

    </table>
</div>

@*<button id="goLive" class="btn btn-success"> Go Live</button>*@
<button id="voteNotify">vote</button>
<script>
    var g_notification = '@ViewBag.Notification';
    if (g_notification == 'True')
        $('#notification').text('1');
    else
        $('#notification').text('0');
</script>
@Scripts.Render("~/Scripts/Base/userMap.js");

Views/Base/LiveMap.cshtml
@model IList<IndianCitizenService.Models.RenderMapDetail>

@{
    ViewBag.Title = "Live Map";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<span class="glyphicon glyphicon-log-out" id="logout"></span>
<div id="livemap" style="width:80%;height:80%;"></div>
<button id="StatusChange" class="btn btn-success" onclick="saveCleanStatus()">
    Clean
</button>
@*<button id="userMap" class="btn btn-success">
        User Service
    </button>*@
<script>
    var g_renderMapDetail = JSON.parse('@Html.Raw(Json.Encode(Model))');
</script>
@Scripts.Render("~/Scripts/Base/liveMap.js")

Views/Base/Logon.cshtml
@{
    ViewBag.Title = "Login";
}

<div id="loginArea">
    <table>
        <tr>
            <td>User Id</td>
            <td><input type="text" class="form-control" id="txtUserid" /></td>
        </tr>
        <tr>
            <td>Password</td>
            <td><input type="password" class="form-control" id="txtPassword" /></td>
        </tr>
        <tr>
            <td colspan="2"><button class="btn btn-primary" id="loginBtn">Login</button></td>
        </tr>
    </table>
</div>

Views/Base/ReportIndex.cshtml
@model int?
@{
    ViewBag.Title = "Reports";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            @if (Model == null)
            {
                <img src="/Base/PieChart" />
            }
            else if (Model == 1)
            {
                <img src="/Base/BarChart" />
            }
            else if (Model == 2)
            {
                <img src="/Base/AreawiseChart" />
            }
            else if (Model == 3)
            {
                <img src="/Base/CityWise" />
            }
            else
            {
                <table class="table" style="border:1px solid">
                    <thead>
                        <tr style="background-color:#293d3d;color:white;">
                            <th>Street Name</th>
                            <th>High</th>
                            <th>Medium</th>
                            <th>Low</th>
                            <th>Concern free</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="danger">
                            <td>Industrial Estate</td>
                            <td>50%</td>
                            <td>20%</td>
                            <td>10%</td>
                            <td>15%</td>
                            <td>Yet to deploy</td>
                            <td><button type="button" class="btn btn-primary">Deploy</button></td>
                        </tr>
                        <tr class="warning">
                            <td>Saibaba Lane</td>
                            <td>40%</td>
                            <td>20%</td>
                            <td>10%</td>
                            <td>25%</td>
                            <td>deployed</td>
                            <td><button type="button" disabled="disabled" class="btn btn-primary">Deploy</button></td>
                        </tr>
                        <tr class="warning">
                            <td>Station Road</td>
                            <td>30%</td>
                            <td>30%</td>
                            <td>10%</td>
                            <td>25%</td>
                            <td>Work in progress</td>
                            <td><button type="button" disabled="disabled" class="btn btn-primary">Deploy</button></td>
                        </tr>
                        <tr class="warning">
                            <td>Labour Colny 6th Cross Street</td>
                            <td>28%</td>
                            <td>18%</td>
                            <td>30%</td>
                            <td>15%</td>
                            <td>deployed</td>
                            <td><button type="button" disabled="disabled" class="btn btn-primary">Deploy</button></td>
                        </tr>
                        <tr class="success">
                            <td>Kathipara Road</td>
                            <td>0%</td>
                            <td>0%</td>
                            <td>0%</td>
                            <td>100%</td>
                            <td>Cleaned</td>
                            <td><button type="button" class="btn btn-primary" disabled="disabled">Deploy</button></td>

                        </tr>
                    </tbody>
                </table>


            }
        </div>
        <div class="col-md-2">
        </div>
    </div>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <!-- Google map API-->
    <script src="http://maps.googleapis.com/maps/api/js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


    <script>
        var categoryColors = ["#ff0000", "#FFA500", "#FFFF00", "#008000", "#00FFFF"];//category colors
    </script>
</head>
<body>
    
    <header><center>INDIAN CITIZEN SERVICE</center></header>
    @RenderBody()
    <footer><center>Made with &hearts; in India</center></footer>  
</body>
</html>

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="http://maps.googleapis.com/maps/api/js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        var selectedCategory = 5;//default road color
        var userMapUrl = '@Url.Action("Index", "Base")';
        var liveMapUrl = '@Url.Action("LiveMap","Base")';
        var categoryColors = ["#ff0000", "#FFA500", "#FFFF00", "#008000", "#00FFFF"];//category colors
    </script>
</head>
<body>

    <header><center>INDIAN CITIZEN SERVICE</center></header>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">INDIAN CITIZEN SERVICE</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/Base/LiveMap">Home</a></li>
                    <li><a href="/Base/ReportIndex?reportType=12">Dashboard</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Report <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#"></a></li>
                            <li><a href="/Base/ReportIndex">Overall City Health Status - Pie Chart </a></li>
                            <li><a href="/Base/ReportIndex?reportType=1">Overall City Health Status - Bar chart</a></li>
                            <li><a href="/Base/ReportIndex?reportType=2">Areawise Health Status</a></li>
                            <li><a href="/Base/ReportIndex?reportType=3">Citywise Health Status</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right"></ul>
            </div>
        </div>
    </nav>
    <div class="jumbotron">
        @RenderBody()
    </div>

    <footer><center>Made with &hearts; in India</center></footer>

</body>
</html>